# Generated by Django 4.1.3 on 2022-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
